
package com.dotecofy.improvement.assignment

sealed trait AssignmentRepositoryComponentSub extends AssignmentRepositoryComponent

object AssignmentRepositorySub extends AssignmentRepository with AssignmentRepositoryComponentSub {

}